version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_NAME}
    depends_on:
      - php
    ports:
      - ${HTTP_HOST}:80
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
  php:
    image: php:${PHP_VERSION}-fpm
    container_name: ${PHP_NAME}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP_CONFIG_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONFIG_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_NAME}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
  redis:
    image: redis:${REDIS_VERSION}
    container_name: ${REDIS_NAME}
    #command: ["redis-server", "/etc/redis/redis.conf"]
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - ${REDIS_DATA_DIR}:/data/:rw
        #- ${REDIS_CONFIG_DIR}:/etc/redis/redis.conf:rw
    restart: always
